/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorVenta;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.vo.Categoria;
import modelo.vo.Cliente;
import modelo.vo.Pedido;
import modelo.vo.Producto;
//import modelo.vo.Usuario;
import modelo.vo.Venta;

/**
 *
 * @author Cesar
 */
public class PanelVentas extends javax.swing.JPanel {

    // ATRIBUTOS DE CLASE
    ControladorVenta miControladorVenta;
    private DefaultTableModel miDefaultTableModel;

    /**
     * Creates new form PanelVentas
     */
    public PanelVentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panEncabezado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panCuerpo = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDni = new jtextfieldround.JTextFieldRound();
        txtRuc = new jtextfieldround.JTextFieldRound();
        txtNombre = new jtextfieldround.JTextFieldRound();
        txtApellido = new jtextfieldround.JTextFieldRound();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPedido = tblPedido = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;//Disallow the editing of any cell
            }
        };
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtIdProd = new jtextfieldround.JTextFieldRound();
        txtNomProd = new jtextfieldround.JTextFieldRound();
        txtCantProd = new jtextfieldround.JTextFieldRound();
        txtPrecioProd = new jtextfieldround.JTextFieldRound();
        txtCategoria = new jtextfieldround.JTextFieldRound();
        btnAgregarPedido = new javax.swing.JButton();
        btnBorrarProd = new javax.swing.JButton();
        btnBuscarProd = new javax.swing.JButton();
        btnModificarProd = new javax.swing.JButton();
        btnVenta = new javax.swing.JButton();
        txtTotal = new jtextfieldround.JTextFieldRound();
        btnCancelarVenta = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setMinimumSize(new java.awt.Dimension(1120, 690));
        setPreferredSize(new java.awt.Dimension(1120, 690));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panEncabezado.setBackground(new java.awt.Color(44, 80, 154));
        panEncabezado.setPreferredSize(new java.awt.Dimension(1120, 40));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ventas");

        javax.swing.GroupLayout panEncabezadoLayout = new javax.swing.GroupLayout(panEncabezado);
        panEncabezado.setLayout(panEncabezadoLayout);
        panEncabezadoLayout.setHorizontalGroup(
            panEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(1086, Short.MAX_VALUE))
        );
        panEncabezadoLayout.setVerticalGroup(
            panEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        add(panEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1132, -1));

        panCuerpo.setBackground(new java.awt.Color(57, 103, 196));
        panCuerpo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(50, 133, 203));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(70, 106, 124));
        jLabel12.setFont(new java.awt.Font("Roboto", 1, 14));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("DNI");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 39, -1, -1));

        jLabel13.setBackground(new java.awt.Color(70, 106, 124));
        jLabel13.setFont(new java.awt.Font("Roboto", 1, 14));
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Apellido");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 113, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cliente");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, -1, -1));

        jLabel18.setBackground(new java.awt.Color(70, 106, 124));
        jLabel18.setFont(new java.awt.Font("Roboto", 1, 14));
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("RUC");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 39, -1, -1));

        jLabel11.setBackground(new java.awt.Color(70, 106, 124));
        jLabel11.setFont(new java.awt.Font("Roboto", 1, 14));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nombre");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 75, -1, -1));

        txtDni.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDni.setFont(new java.awt.Font("Roboto", 0, 14));
        jPanel2.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 35, 126, -1));

        txtRuc.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtRuc.setFont(new java.awt.Font("Roboto", 0, 14));
        jPanel2.add(txtRuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 35, 195, -1));

        txtNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombre.setFont(new java.awt.Font("Roboto", 0, 14));
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 70, 375, -1));

        txtApellido.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtApellido.setFont(new java.awt.Font("Roboto", 0, 14));
        jPanel2.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 109, 373, -1));

        panCuerpo.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 450, 150));

        jLabel17.setBackground(new java.awt.Color(70, 106, 124));
        jLabel17.setFont(new java.awt.Font("Roboto", 1, 14));
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("TOTAL");
        panCuerpo.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 580, -1, -1));

        tblPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PRODUCTO", "CATEGORIA", "CANTIDAD", "PRECIO", "MONTO"
            }
        ));
        tblPedido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblPedidoFocusGained(evt);
            }
        });
        jScrollPane2.setViewportView(tblPedido);

        panCuerpo.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 181, 1100, 360));

        jPanel3.setBackground(new java.awt.Color(50, 133, 203));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(70, 106, 124));
        jLabel14.setFont(new java.awt.Font("Roboto", 1, 14));
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("IdProducto");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 45, -1, -1));

        jLabel15.setBackground(new java.awt.Color(70, 106, 124));
        jLabel15.setFont(new java.awt.Font("Roboto", 1, 14));
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Categoria");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 45, -1, -1));

        jLabel16.setBackground(new java.awt.Color(70, 106, 124));
        jLabel16.setFont(new java.awt.Font("Roboto", 1, 14));
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Cantidad");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 123, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 18));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Producto");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, -1, -1));

        jLabel19.setBackground(new java.awt.Color(70, 106, 124));
        jLabel19.setFont(new java.awt.Font("Roboto", 1, 14));
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Precio");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 125, -1, -1));

        jLabel20.setBackground(new java.awt.Color(70, 106, 124));
        jLabel20.setFont(new java.awt.Font("Roboto", 1, 14));
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Nombre");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 85, -1, -1));

        txtIdProd.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtIdProd.setFont(new java.awt.Font("Roboto", 0, 14));
        txtIdProd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdProdFocusGained(evt);
            }
        });
        jPanel3.add(txtIdProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 41, 160, -1));

        txtNomProd.setEditable(false);
        txtNomProd.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNomProd.setFont(new java.awt.Font("Roboto", 0, 14));
        jPanel3.add(txtNomProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 81, 350, -1));

        txtCantProd.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCantProd.setFont(new java.awt.Font("Roboto", 0, 14));
        jPanel3.add(txtCantProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 119, 160, -1));

        txtPrecioProd.setEditable(false);
        txtPrecioProd.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPrecioProd.setFont(new java.awt.Font("Roboto", 0, 14));
        jPanel3.add(txtPrecioProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 119, 120, -1));

        txtCategoria.setEditable(false);
        txtCategoria.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtCategoria.setFont(new java.awt.Font("Roboto", 0, 14));
        jPanel3.add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 41, 120, -1));

        panCuerpo.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 450, 150));

        btnAgregarPedido.setBackground(new java.awt.Color(40, 35, 127));
        btnAgregarPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/agregar.png"))); // NOI18N
        btnAgregarPedido.setToolTipText("Agregar");
        btnAgregarPedido.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(50, 133, 203))); // NOI18N
        btnAgregarPedido.setBorderPainted(false);
        btnAgregarPedido.setContentAreaFilled(false);
        btnAgregarPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAgregarPedido.setFocusPainted(false);
        btnAgregarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPedidoActionPerformed(evt);
            }
        });
        panCuerpo.add(btnAgregarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(982, 10, 65, 65));

        btnBorrarProd.setBackground(new java.awt.Color(44, 80, 154));
        btnBorrarProd.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/eliminar.png"))); // NOI18N
        btnBorrarProd.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(50, 133, 203))); // NOI18N
        btnBorrarProd.setBorderPainted(false);
        btnBorrarProd.setContentAreaFilled(false);
        btnBorrarProd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBorrarProd.setFocusPainted(false);
        btnBorrarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarProdActionPerformed(evt);
            }
        });
        panCuerpo.add(btnBorrarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, 65, 65));

        btnBuscarProd.setBackground(new java.awt.Color(44, 80, 154));
        btnBuscarProd.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/buscar.png"))); // NOI18N
        btnBuscarProd.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(50, 133, 203))); // NOI18N
        btnBuscarProd.setBorderPainted(false);
        btnBuscarProd.setContentAreaFilled(false);
        btnBuscarProd.setEnabled(false);
        btnBuscarProd.setFocusPainted(false);
        panCuerpo.add(btnBuscarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(982, 79, 65, 65));

        btnModificarProd.setBackground(new java.awt.Color(44, 80, 154));
        btnModificarProd.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/editar.png"))); // NOI18N
        btnModificarProd.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(50, 133, 203))); // NOI18N
        btnModificarProd.setBorderPainted(false);
        btnModificarProd.setContentAreaFilled(false);
        btnModificarProd.setFocusPainted(false);
        btnModificarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarProdActionPerformed(evt);
            }
        });
        panCuerpo.add(btnModificarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 79, 65, 65));

        btnVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/carrito-de-compras.png"))); // NOI18N
        btnVenta.setBorderPainted(false);
        btnVenta.setContentAreaFilled(false);
        btnVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaActionPerformed(evt);
            }
        });
        panCuerpo.add(btnVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 75, -1));

        txtTotal.setEditable(false);
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        panCuerpo.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 580, 129, -1));

        btnCancelarVenta.setText("Cancelar venta");
        btnCancelarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarVentaActionPerformed(evt);
            }
        });
        panCuerpo.add(btnCancelarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 570, -1, -1));

        add(panCuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1120, 650));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPedidoActionPerformed
        // TODO add your handling code here:
        miControladorVenta.registrarPedido();
    }//GEN-LAST:event_btnAgregarPedidoActionPerformed

    private void btnBorrarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarProdActionPerformed
        // TODO add your handling code here:
        miControladorVenta.eliminarPedido();
    }//GEN-LAST:event_btnBorrarProdActionPerformed

    private void btnModificarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarProdActionPerformed
        // TODO add your handling code here:
        miControladorVenta.modificarPedido();
    }//GEN-LAST:event_btnModificarProdActionPerformed

    private void btnVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaActionPerformed
        // TODO add your handling code here:
        miControladorVenta.registrarVenta();
        miControladorVenta.registrarCliente();
    }//GEN-LAST:event_btnVentaActionPerformed

    private void tblPedidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblPedidoFocusGained
        // TODO add your handling code here:
        miControladorVenta.buscarPedido();
    }//GEN-LAST:event_tblPedidoFocusGained

    private void txtIdProdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdProdFocusGained
        // TODO add your handling code here:
        limpiarCamposPanelProducto();
    }//GEN-LAST:event_txtIdProdFocusGained

    private void btnCancelarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarVentaActionPerformed
        // TODO add your handling code here:
        miControladorVenta.eliminarCarritoPedidos();
    }//GEN-LAST:event_btnCancelarVentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregarPedido;
    public javax.swing.JButton btnBorrarProd;
    public javax.swing.JButton btnBuscarProd;
    private javax.swing.JButton btnCancelarVenta;
    public javax.swing.JButton btnModificarProd;
    private javax.swing.JButton btnVenta;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel11;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel18;
    public javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panCuerpo;
    private javax.swing.JPanel panEncabezado;
    public javax.swing.JTable tblPedido;
    private jtextfieldround.JTextFieldRound txtApellido;
    public jtextfieldround.JTextFieldRound txtCantProd;
    private jtextfieldround.JTextFieldRound txtCategoria;
    public jtextfieldround.JTextFieldRound txtDni;
    public jtextfieldround.JTextFieldRound txtIdProd;
    private jtextfieldround.JTextFieldRound txtNomProd;
    private jtextfieldround.JTextFieldRound txtNombre;
    private jtextfieldround.JTextFieldRound txtPrecioProd;
    private jtextfieldround.JTextFieldRound txtRuc;
    private jtextfieldround.JTextFieldRound txtTotal;
    // End of variables declaration//GEN-END:variables

    public void setControlador(ControladorVenta miControladorVenta) {
        this.miControladorVenta = miControladorVenta;
    }

    // MÉTODOS AUXILIARES
    public Venta empaquetarDatosVenta(String dniUsuario) {
        Venta miVenta = new Venta();
        miVenta.setDniUsuario(dniUsuario);
        miVenta.setDniCliente(txtDni.getText());
        miVenta.setMonto(Float.parseFloat(txtTotal.getText()));
        miVenta.setBoleta(true); // Agregar checkbox a vista para este campo.
        return miVenta;
    }

    public Pedido empaquetarDatosPedido() {
        Pedido miPedido = new Pedido();
        miPedido.setIdVenta(miControladorVenta.generarIdVenta());
        miPedido.setIdProducto(Integer.parseInt(txtIdProd.getText()));
        miPedido.setCantidad(Integer.parseInt(txtCantProd.getText()));
        return miPedido;
    }

    public Cliente empaquetarDatosCliente() {
        Cliente miCliente = new Cliente();
        miCliente.setDniCliente(txtDni.getText());
        miCliente.setNombre(txtNombre.getText());
        miCliente.setApellido(txtApellido.getText());
        miCliente.setRuc(txtRuc.getText());
        return miCliente;
    }

    public void limpiarCamposPanelProducto() {
        txtIdProd.setText("");
        txtCantProd.setText("");
        txtCategoria.setText("");
        txtNomProd.setText("");
        txtPrecioProd.setText("");
        txtIdProd.requestFocus();
    }

    public void limpiarCamposPanelCliente() {
        txtDni.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtRuc.setText("");
        txtTotal.setText("");
        txtDni.requestFocus();
    }

    public void setTablaPedido(ArrayList<Pedido> carritoPedidos, ArrayList<Categoria> misCategorias) {
        String[] columnas = {"ID", "Producto", "Categoria", "Cantidad", "Precio", "Monto"};
        Object[][] miData = new Object[carritoPedidos.size()][6];
        Producto miProducto;
        float precio;
        int cantidad;
        float total = 0;

        for (int i = 0; i < carritoPedidos.size(); i++) {
            miProducto = miControladorVenta.buscarIdProducto(carritoPedidos.get(i).getIdProducto());
            precio = miProducto.getPrecio();
            cantidad = carritoPedidos.get(i).getCantidad();

            miData[i][0] = carritoPedidos.get(i).getIdPedido();
            miData[i][1] = miProducto.getNombre();
            miData[i][3] = cantidad;
            miData[i][4] = precio;
            miData[i][5] = precio * cantidad;
            total += precio * cantidad;

            for (int j = 0; j < misCategorias.size(); j++) {
                if (misCategorias.get(j).getIdCategoria() == miProducto.getIdCategoria()) {
                    miData[i][2] = misCategorias.get(j).getNombreCategoria();
                }
            }
        }

        miDefaultTableModel = new DefaultTableModel(miData, columnas);
        tblPedido.setModel(miDefaultTableModel);
        txtTotal.setText("" + total);
    }

    public void desempaquetarDatosProducto(Producto miProducto, Categoria miCategoria) {
        txtNomProd.setText(miProducto.getNombre());
        txtCategoria.setText(miCategoria.getNombreCategoria());
        txtPrecioProd.setText("" + miProducto.getPrecio());
    }

    public void desempaquetarDatosPedido(Pedido miPedido) {
        txtIdProd.setText("" + miPedido.getIdProducto());
        txtCantProd.setText("" + miPedido.getCantidad());
        txtCantProd.requestFocus();
    }

    public int idPedidoSeleccionado() {
        int idPedidoSelecionado = -1;
        if (tblPedido.getSelectedRow() != -1) {
            idPedidoSelecionado = (Integer) tblPedido.getValueAt(tblPedido.getSelectedRow(), 0);
        }
        return idPedidoSelecionado;
    }
}
