/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorUsuario;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.vo.Usuario;

/**
 *
 * @author krypt97
 */
public class PanelUsuarios extends javax.swing.JPanel {
    ControladorUsuario miControladorUsuario;
    private DefaultTableModel miDefaultTableModel;

    /**
     * Creates new form NewPanelUsuarios
     */
    public PanelUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panEncabezado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panCuerpo = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        lblImg = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cboxRol = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = tblUsuarios = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;//Disallow the editing of any cell
            }
        };
        txtDni = new jtextfieldround.JTextFieldRound();
        txtUsuario = new jtextfieldround.JTextFieldRound();
        txtNombre = new jtextfieldround.JTextFieldRound();
        txtApellido = new jtextfieldround.JTextFieldRound();
        txtContrasenia = new jtextfieldround.JTextFieldRound();

        setMinimumSize(new java.awt.Dimension(1120, 690));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1120, 690));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panEncabezado.setBackground(new java.awt.Color(44, 80, 154));
        panEncabezado.setMinimumSize(new java.awt.Dimension(1120, 40));
        panEncabezado.setPreferredSize(new java.awt.Dimension(1120, 40));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Usuarios");
        jLabel1.setPreferredSize(new java.awt.Dimension(183, 44));

        javax.swing.GroupLayout panEncabezadoLayout = new javax.swing.GroupLayout(panEncabezado);
        panEncabezado.setLayout(panEncabezadoLayout);
        panEncabezadoLayout.setHorizontalGroup(
            panEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panEncabezadoLayout.setVerticalGroup(
            panEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        add(panEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panCuerpo.setBackground(new java.awt.Color(57, 103, 196));
        panCuerpo.setPreferredSize(new java.awt.Dimension(1120, 650));
        panCuerpo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setBackground(new java.awt.Color(102, 102, 102));
        btnAgregar.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/agregar.png"))); // NOI18N
        btnAgregar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));
        btnAgregar.setBorderPainted(false);
        btnAgregar.setContentAreaFilled(false);
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        panCuerpo.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(982, 10, 65, 65));

        btnEliminar.setBackground(new java.awt.Color(102, 102, 102));
        btnEliminar.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/eliminar.png"))); // NOI18N
        btnEliminar.setToolTipText("");
        btnEliminar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        panCuerpo.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, 65, 65));

        btnBuscar.setBackground(new java.awt.Color(102, 102, 102));
        btnBuscar.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/buscar.png"))); // NOI18N
        btnBuscar.setToolTipText("");
        btnBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));
        btnBuscar.setBorderPainted(false);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        panCuerpo.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(982, 79, 65, 65));

        btnModificar.setBackground(new java.awt.Color(102, 102, 102));
        btnModificar.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/editar.png"))); // NOI18N
        btnModificar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")));
        btnModificar.setBorderPainted(false);
        btnModificar.setContentAreaFilled(false);
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        panCuerpo.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 79, 65, 65));

        lblImg.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblImg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImg.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblImg.setOpaque(true);
        panCuerpo.add(lblImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 19, 120, 120));

        jLabel9.setBackground(new java.awt.Color(70, 106, 124));
        jLabel9.setFont(new java.awt.Font("Roboto", 1, 16));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DNI");
        panCuerpo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 28, -1, -1));

        jLabel11.setBackground(new java.awt.Color(70, 106, 124));
        jLabel11.setFont(new java.awt.Font("Roboto", 1, 16));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nombres");
        panCuerpo.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 70, 70, 18));

        jLabel10.setBackground(new java.awt.Color(70, 106, 124));
        jLabel10.setFont(new java.awt.Font("Roboto", 1, 16));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Apellidos");
        panCuerpo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 70, 84, 19));

        jLabel12.setBackground(new java.awt.Color(70, 106, 124));
        jLabel12.setFont(new java.awt.Font("Roboto", 1, 16));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Usuario");
        panCuerpo.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 111, 70, 19));

        jLabel14.setBackground(new java.awt.Color(70, 106, 124));
        jLabel14.setFont(new java.awt.Font("Roboto", 1, 16));
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Rol");
        panCuerpo.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 28, -1, -1));

        cboxRol.setFont(new java.awt.Font("Roboto", 0, 14));
        cboxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VENDEDOR", "ADMINISTRADOR" }));
        panCuerpo.add(cboxRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 23, 300, 27));

        jLabel13.setBackground(new java.awt.Color(70, 106, 124));
        jLabel13.setFont(new java.awt.Font("Roboto", 1, 16));
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Contraseña");
        panCuerpo.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 111, 90, 19));

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        tblUsuarios.setDoubleBuffered(true);
        tblUsuarios.setMinimumSize(new java.awt.Dimension(1100, 440));
        tblUsuarios.setPreferredSize(null);
        tblUsuarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblUsuarios.setShowGrid(true);
        jScrollPane1.setViewportView(tblUsuarios);

        panCuerpo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 181, 1100, 440));

        txtDni.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDni.setFont(new java.awt.Font("Roboto", 0, 14));
        panCuerpo.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 23, 300, 27));

        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUsuario.setFont(new java.awt.Font("Roboto", 0, 14));
        panCuerpo.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 108, 300, 27));

        txtNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombre.setFont(new java.awt.Font("Roboto", 0, 14));
        panCuerpo.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 65, 300, 27));

        txtApellido.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtApellido.setFont(new java.awt.Font("Roboto", 0, 14));
        panCuerpo.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 65, 300, 27));

        txtContrasenia.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtContrasenia.setFont(new java.awt.Font("Roboto", 0, 14));
        panCuerpo.add(txtContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 108, 300, 27));

        add(panCuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        miControladorUsuario.registrarUsuario();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        miControladorUsuario.modificarUsuario();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        miControladorUsuario.eliminarUsuario();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        miControladorUsuario.buscarUsuario();
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cboxRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImg;
    private javax.swing.JPanel panCuerpo;
    private javax.swing.JPanel panEncabezado;
    private javax.swing.JTable tblUsuarios;
    private jtextfieldround.JTextFieldRound txtApellido;
    private jtextfieldround.JTextFieldRound txtContrasenia;
    public jtextfieldround.JTextFieldRound txtDni;
    private jtextfieldround.JTextFieldRound txtNombre;
    private jtextfieldround.JTextFieldRound txtUsuario;
    // End of variables declaration//GEN-END:variables

    // ENLACE CONTROLADOR
    public void setControlador(ControladorUsuario miControladorUsuario) {
        this.miControladorUsuario = miControladorUsuario;
    }

    // MÉTODOS AUXILIARES
    public Usuario empaquetarDatosUsuario() {
        Usuario miUsuario = new Usuario();
        miUsuario.setDniUsuario(txtDni.getText());
        miUsuario.setNombre(txtNombre.getText());
        miUsuario.setApellido(txtApellido.getText());
        miUsuario.setUsername(txtUsuario.getText());
        miUsuario.setPassword(txtContrasenia.getText());
        miUsuario.setRol((String)cboxRol.getSelectedItem());
        return miUsuario;
    }
    
    public void setTablaUsuarios(ArrayList<Usuario> miArrayList) {
        String[] columnas = {"DNI", "Apellido", "Nombre", "Usuario", "Contraseña", "Rol"};
        Object[][] miData = new Object[miArrayList.size()][6];
        for (int i = 0; i < miArrayList.size(); i++) {
            miData[i][0] = miArrayList.get(i).getDniUsuario();
            miData[i][1] = miArrayList.get(i).getApellido();
            miData[i][2] = miArrayList.get(i).getNombre();
            miData[i][3] = miArrayList.get(i).getUsername();
            miData[i][4] = miArrayList.get(i).getPassword();
            miData[i][5] = miArrayList.get(i).getRol();
        }
        miDefaultTableModel = new DefaultTableModel(miData, columnas);
        tblUsuarios.setModel(miDefaultTableModel);
    }
    
    public void desempaquetarDatosUsuario(Usuario miUsuario) {
        txtNombre.setText(miUsuario.getNombre());
        txtApellido.setText(miUsuario.getApellido());
        txtUsuario.setText(miUsuario.getUsername());
        txtContrasenia.setText(miUsuario.getPassword());
        
        if (miUsuario.getRol().equals("VENDEDOR")) {
            cboxRol.setSelectedIndex(0);
        }
        else {
            cboxRol.setSelectedIndex(1);
        }
    }
    
    public void limpiarCampos() {
        txtDni.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtUsuario.setText("");
        txtContrasenia.setText("");
        txtDni.requestFocus();
    }
}
