/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorHistorialVenta;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.vo.Categoria;
import modelo.vo.Cliente;
import modelo.vo.Pedido;
import modelo.vo.Producto;
import modelo.vo.Usuario;
import modelo.vo.Venta;

/**
 *
 * @author Daniel
 */
public class PanelHistorialVentas extends javax.swing.JPanel {

    private ControladorHistorialVenta miControladorHistorialVenta;

    /**
     * Creates new form NewPanelUsuarios
     */
    public PanelHistorialVentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panEncabezado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panCuerpo = new javax.swing.JPanel();
        panVent = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblVenta = tblVenta = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;//Disallow the editing of any cell
            }
        };
        panDet = new javax.swing.JPanel();
        txtNombreVendedor = new jtextfieldround.JTextFieldRound();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreCliente = new jtextfieldround.JTextFieldRound();
        jLabel4 = new javax.swing.JLabel();
        txtApellidoVendedor = new jtextfieldround.JTextFieldRound();
        jLabel5 = new javax.swing.JLabel();
        txtApellidoCliente = new jtextfieldround.JTextFieldRound();
        panProd = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPedidos = tblPedidos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;//Disallow the editing of any cell
            }
        };

        setMinimumSize(new java.awt.Dimension(1120, 690));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1120, 690));
        setRequestFocusEnabled(false);
        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(57, 103, 196));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(1120, 690));
        jPanel2.setPreferredSize(new java.awt.Dimension(1120, 690));
        jPanel2.setLayout(new java.awt.BorderLayout());

        panEncabezado.setBackground(new java.awt.Color(44, 80, 154));
        panEncabezado.setMaximumSize(null);
        panEncabezado.setMinimumSize(new java.awt.Dimension(1120, 40));
        panEncabezado.setPreferredSize(new java.awt.Dimension(1120, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Historial de ventas");
        jLabel1.setPreferredSize(new java.awt.Dimension(183, 44));

        javax.swing.GroupLayout panEncabezadoLayout = new javax.swing.GroupLayout(panEncabezado);
        panEncabezado.setLayout(panEncabezadoLayout);
        panEncabezadoLayout.setHorizontalGroup(
            panEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(720, Short.MAX_VALUE))
        );
        panEncabezadoLayout.setVerticalGroup(
            panEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(panEncabezado, java.awt.BorderLayout.NORTH);

        panCuerpo.setBackground(new java.awt.Color(57, 103, 196));
        panCuerpo.setMaximumSize(null);
        panCuerpo.setMinimumSize(new java.awt.Dimension(1120, 650));
        panCuerpo.setPreferredSize(new java.awt.Dimension(1120, 650));

        panVent.setBackground(new java.awt.Color(57, 103, 196));
        panVent.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ventas realizadas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        panVent.setMinimumSize(new java.awt.Dimension(1120, 650));
        panVent.setPreferredSize(new java.awt.Dimension(1120, 250));
        panVent.setRequestFocusEnabled(false);
        panVent.setVerifyInputWhenFocusTarget(false);

        tblVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Venta", "DNI Vendedor", "DNI Cliente", "Monto"
            }
        ));
        tblVenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblVentaFocusGained(evt);
            }
        });
        jScrollPane4.setViewportView(tblVenta);

        javax.swing.GroupLayout panVentLayout = new javax.swing.GroupLayout(panVent);
        panVent.setLayout(panVentLayout);
        panVentLayout.setHorizontalGroup(
            panVentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1110, Short.MAX_VALUE)
        );
        panVentLayout.setVerticalGroup(
            panVentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        panDet.setBackground(new java.awt.Color(57, 103, 196));
        panDet.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalle de venta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        panDet.setMinimumSize(new java.awt.Dimension(1120, 50));
        panDet.setPreferredSize(new java.awt.Dimension(1120, 150));

        txtNombreVendedor.setEditable(false);
        txtNombreVendedor.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombreVendedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setBackground(new java.awt.Color(70, 106, 124));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre del vendedor");

        jLabel3.setBackground(new java.awt.Color(70, 106, 124));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre del cliente");

        txtNombreCliente.setEditable(false);
        txtNombreCliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNombreCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setBackground(new java.awt.Color(70, 106, 124));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellidos del venedor");

        txtApellidoVendedor.setEditable(false);
        txtApellidoVendedor.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtApellidoVendedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setBackground(new java.awt.Color(70, 106, 124));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellidos del cliente");

        txtApellidoCliente.setEditable(false);
        txtApellidoCliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtApellidoCliente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout panDetLayout = new javax.swing.GroupLayout(panDet);
        panDet.setLayout(panDetLayout);
        panDetLayout.setHorizontalGroup(
            panDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDetLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombreVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtApellidoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(40, 40, 40))
        );
        panDetLayout.setVerticalGroup(
            panDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDetLayout.createSequentialGroup()
                .addGroup(panDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panDetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidoVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        panProd.setBackground(new java.awt.Color(57, 103, 196));
        panProd.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Productos comprados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        panProd.setPreferredSize(new java.awt.Dimension(1120, 250));

        tblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Categoria", "Cantidad", "Precio"
            }
        ));
        jScrollPane3.setViewportView(tblPedidos);

        javax.swing.GroupLayout panProdLayout = new javax.swing.GroupLayout(panProd);
        panProd.setLayout(panProdLayout);
        panProdLayout.setHorizontalGroup(
            panProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        panProdLayout.setVerticalGroup(
            panProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panCuerpoLayout = new javax.swing.GroupLayout(panCuerpo);
        panCuerpo.setLayout(panCuerpoLayout);
        panCuerpoLayout.setHorizontalGroup(
            panCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panDet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panCuerpoLayout.createSequentialGroup()
                .addComponent(panVent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panCuerpoLayout.setVerticalGroup(
            panCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCuerpoLayout.createSequentialGroup()
                .addComponent(panVent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panDet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panProd, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE))
        );

        jPanel2.add(panCuerpo, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tblVentaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblVentaFocusGained
        // TODO add your handling code here:
        miControladorHistorialVenta.cargarPedidosSeleccionados();
    }//GEN-LAST:event_tblVentaFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel panCuerpo;
    private javax.swing.JPanel panDet;
    private javax.swing.JPanel panEncabezado;
    private javax.swing.JPanel panProd;
    private javax.swing.JPanel panVent;
    public javax.swing.JTable tblPedidos;
    public javax.swing.JTable tblVenta;
    private jtextfieldround.JTextFieldRound txtApellidoCliente;
    private jtextfieldround.JTextFieldRound txtApellidoVendedor;
    private jtextfieldround.JTextFieldRound txtNombreCliente;
    private jtextfieldround.JTextFieldRound txtNombreVendedor;
    // End of variables declaration//GEN-END:variables

    // ENLACE CONTROLADOR
    public void setControlador(ControladorHistorialVenta miControladorHistorialVenta) {
        this.miControladorHistorialVenta = miControladorHistorialVenta;
    }
    
    // MÉTODOS AUXILIARES
    public void setTablaVentas(ArrayList<Venta> misVentas) {
        String[] columnas = {"ID Venta", "DNI Vendedor", "DNI Cliente", "Monto"};
        Object[][] miData = new Object[misVentas.size()][4];
        for (int i = 0; i < misVentas.size(); i++) {
            miData[i][0] = misVentas.get(i).getIdVenta();
            miData[i][1] = misVentas.get(i).getDniUsuario();
            miData[i][2] = misVentas.get(i).getDniCliente();
            miData[i][3] = misVentas.get(i).getMonto();
        }
        DefaultTableModel miDefaultTableModel = new DefaultTableModel(miData, columnas);
        tblVenta.setModel(miDefaultTableModel);
    }
    
    // Método por mejorar.
    public void SetTablaPedidos(ArrayList<Pedido> listaCarritoPedidos, ArrayList<Producto> misProductos, ArrayList<Categoria> misCategorias) {
        String[] columnas = {"Producto", "Categoria", "Cantidad", "Precio"};
        Object[][] miData = new Object[listaCarritoPedidos.size()][4];
        Producto miProductoBuscado = new Producto();
        
        for (int i = 0; i < miData.length; i++) {
            miData[i][2] = listaCarritoPedidos.get(i).getCantidad();
            
            for (int j = 0; j < misProductos.size(); j++) {
                miProductoBuscado = misProductos.get(j);
                if (miProductoBuscado.getIdProducto() == listaCarritoPedidos.get(i).getIdProducto()) {
                    miData[i][0] = miProductoBuscado.getNombre();
                    miData[i][3] = miProductoBuscado.getPrecio();
                    break;
                }
            }
            
            for (int j = 0; j < misCategorias.size(); j++) {
                if (miProductoBuscado.getIdCategoria() == misCategorias.get(j).getIdCategoria()) {
                    miData[i][1] = misCategorias.get(j).getNombreCategoria();
                }
            }
        }
        
        DefaultTableModel miDefaultTableModel = new DefaultTableModel(miData, columnas);
        tblPedidos.setModel(miDefaultTableModel);
    }

    public int idVentaSeleccionado() {
        int idVentaSeleccionado = -1;
        if (tblVenta.getSelectedRow() != -1) {
            idVentaSeleccionado = (int) tblVenta.getValueAt(tblVenta.getSelectedRow(), 0);
        }
        return idVentaSeleccionado;
    }
    
    public String dniUsuarioSeleccionado() {
        String dniUsuarioSelecionado = "";
        if (tblVenta.getSelectedRow() != -1) {
            dniUsuarioSelecionado = (String) tblVenta.getValueAt(tblVenta.getSelectedRow(), 1);
        }
        return dniUsuarioSelecionado;
    }
    
    public String dniClienteSeleccionado() {
        String dniClienteSeleccionado = "";
        if (tblVenta.getSelectedRow() != -1) {
            dniClienteSeleccionado = (String) tblVenta.getValueAt(tblVenta.getSelectedRow(), 2);
        }
        return dniClienteSeleccionado;
    }

    public void desempaquetarDatosUsuario(Usuario miUsuario) {
        txtNombreVendedor.setText(miUsuario.getNombre());
        txtApellidoVendedor.setText(miUsuario.getApellido());
    }

    public void desempaquetarDatosCliente(Cliente miCliente) {
        txtNombreCliente.setText(miCliente.getNombre());
        txtApellidoCliente.setText(miCliente.getApellido());
    }
}
