/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorCliente;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.vo.Cliente;
import modelo.vo.Usuario;
import modelo.vo.Venta;

/**
 *
 * @author Daniel
 */
public class PanelClientes extends javax.swing.JPanel {

    private ControladorCliente miControladorCliente;

    /**
     * Creates new form NewPanelUsuarios
     */
    public PanelClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panEncabezado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panCuerpo = new javax.swing.JPanel();
        panHist = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = tblCliente = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;//Disallow the editing of any cell
            }
        };
        panNCompras = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVenta = tblVenta = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex,int colIndex){
                return false;//Disallow the editing of any cell
            }
        };

        setMinimumSize(new java.awt.Dimension(1120, 690));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1120, 690));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(57, 103, 196));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(1120, 690));
        jPanel2.setPreferredSize(new java.awt.Dimension(1120, 690));
        jPanel2.setLayout(new java.awt.BorderLayout());

        panEncabezado.setBackground(new java.awt.Color(44, 80, 154));
        panEncabezado.setMinimumSize(new java.awt.Dimension(1120, 40));
        panEncabezado.setName(""); // NOI18N
        panEncabezado.setPreferredSize(new java.awt.Dimension(1120, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Clientes");
        jLabel1.setPreferredSize(new java.awt.Dimension(183, 44));

        javax.swing.GroupLayout panEncabezadoLayout = new javax.swing.GroupLayout(panEncabezado);
        panEncabezado.setLayout(panEncabezadoLayout);
        panEncabezadoLayout.setHorizontalGroup(
            panEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEncabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(809, Short.MAX_VALUE))
        );
        panEncabezadoLayout.setVerticalGroup(
            panEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(panEncabezado, java.awt.BorderLayout.NORTH);

        panCuerpo.setBackground(new java.awt.Color(57, 103, 196));
        panCuerpo.setMinimumSize(new java.awt.Dimension(1120, 650));
        panCuerpo.setPreferredSize(new java.awt.Dimension(1120, 650));

        panHist.setBackground(new java.awt.Color(57, 103, 196));
        panHist.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Historial de clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        panHist.setForeground(new java.awt.Color(255, 255, 255));
        panHist.setMinimumSize(new java.awt.Dimension(1120, 325));
        panHist.setPreferredSize(new java.awt.Dimension(1120, 325));

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DNI", "Apellidos", "Nombre", "RUC"
            }
        ));
        tblCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblClienteFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(tblCliente);

        javax.swing.GroupLayout panHistLayout = new javax.swing.GroupLayout(panHist);
        panHist.setLayout(panHistLayout);
        panHistLayout.setHorizontalGroup(
            panHistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1110, Short.MAX_VALUE)
        );
        panHistLayout.setVerticalGroup(
            panHistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHistLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );

        panNCompras.setBackground(new java.awt.Color(57, 103, 196));
        panNCompras.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Número de compras realizadas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        panNCompras.setMinimumSize(new java.awt.Dimension(1120, 325));
        panNCompras.setPreferredSize(new java.awt.Dimension(1120, 325));

        tblVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Venta", "DNI Vendedor", "Nombre Vendedor", "Monto vendido"
            }
        ));
        jScrollPane2.setViewportView(tblVenta);

        javax.swing.GroupLayout panNComprasLayout = new javax.swing.GroupLayout(panNCompras);
        panNCompras.setLayout(panNComprasLayout);
        panNComprasLayout.setHorizontalGroup(
            panNComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        panNComprasLayout.setVerticalGroup(
            panNComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panNComprasLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panCuerpoLayout = new javax.swing.GroupLayout(panCuerpo);
        panCuerpo.setLayout(panCuerpoLayout);
        panCuerpoLayout.setHorizontalGroup(
            panCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panHist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panNCompras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panCuerpoLayout.setVerticalGroup(
            panCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCuerpoLayout.createSequentialGroup()
                .addComponent(panHist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panNCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(panCuerpo, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void tblClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblClienteFocusGained
        // TODO add your handling code here:
        miControladorCliente.cargarVentasSeleccionadas();
    }//GEN-LAST:event_tblClienteFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panCuerpo;
    private javax.swing.JPanel panEncabezado;
    private javax.swing.JPanel panHist;
    private javax.swing.JPanel panNCompras;
    public javax.swing.JTable tblCliente;
    public javax.swing.JTable tblVenta;
    // End of variables declaration//GEN-END:variables

    // ENLACE CONTROLADOR
    public void setControlador(ControladorCliente miControladorCliente) {
        this.miControladorCliente = miControladorCliente;
    }

    // MÉTODOS AUXILIARES
    public void setTablaClientes(ArrayList<Cliente> misClientes) {
        String[] columnas = {"DNI", "Apellido", "Nombre", "RUC"};
        Object[][] miData = new Object[misClientes.size()][4];
        for (int i = 0; i < misClientes.size(); i++) {
            miData[i][0] = misClientes.get(i).getDniCliente();
            miData[i][1] = misClientes.get(i).getApellido();
            miData[i][2] = misClientes.get(i).getNombre();
            miData[i][3] = misClientes.get(i).getRuc();
        }
        DefaultTableModel miDefaultTableModel = new DefaultTableModel(miData, columnas);
        tblCliente.setModel(miDefaultTableModel);
    }

    // Forma iterativa se puede mejorar generando un metodo en el DAO que te devuela la lista en cuestión.
    public void setTablaVentas(ArrayList<Venta> misVentas, ArrayList<Usuario> misUsuarios, String dniClienteSeleccionado) {
        String[] columnas = {"ID Venta", "DNI Vendedor", "Nombre Vendedor", "Monto vendido"};
        ArrayList<Venta> misVentasSeleccionadas = new ArrayList<>();
        // Recorre todas las ventas y selecciona las que coinciden con dniClienteSeleccionado
        for (int i = 0; i < misVentas.size(); i++) {
            if (misVentas.get(i).getDniCliente().equals(dniClienteSeleccionado)) {
                misVentasSeleccionadas.add(misVentas.get(i));
            }
        }
        // Setea la tabla con las ventas seleccionadas
        Object[][] miData = new Object[misVentasSeleccionadas.size()][4];
        for (int i = 0; i < misVentasSeleccionadas.size(); i++) {
            miData[i][0] = misVentasSeleccionadas.get(i).getIdVenta();
            miData[i][1] = misVentasSeleccionadas.get(i).getDniUsuario();
            miData[i][3] = misVentasSeleccionadas.get(i).getMonto();
            for (int j = 0; j < misUsuarios.size(); j++) {
                if (misUsuarios.get(j).getDniUsuario().equals(misVentasSeleccionadas.get(i).getDniUsuario())) {
                    miData[i][2] = misUsuarios.get(j).getNombre();
                }
            }
        }

        DefaultTableModel miDefaultTableModel = new DefaultTableModel(miData, columnas);
        tblVenta.setModel(miDefaultTableModel);
    }

    public String dniClienteSeleccionado() {
        String dniClienteSelecionado = "";
        if (tblCliente.getSelectedRow() != -1) {
            dniClienteSelecionado = (String) tblCliente.getValueAt(tblCliente.getSelectedRow(), 0);
        }
        return dniClienteSelecionado;
    }
}
